name: Release

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
  
jobs:
  Release:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        extra_nix_config: experimental-features = nix-command flakes
    - run: nix run nixpkgs#bash -- ./release.sh
    - run: ls -la
