name: Release

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
  
jobs:
  Release:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3.5.0
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        extra_nix_config: experimental-features = nix-command flakes
    - name: "Release to Internet Archive"
      run: XDG_CONFIG_HOME="$HOME/.config" ./update.sh
    - name: Commit and Push
      if: ${{ env.PUSH== 'true' }}
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add update.sh
        git commit -m "GitHub Action: Raycast version update"
        git push
